### ISSUE TITLE
[Feature request] Resolution?

### ISSUE THREAD

**Issue by Fluxed1** [jlesage/docker-firefox#241]
### Idea

i would like to be able to change the resolution. sorry if this is already possible.

**Comment by jlesage** [comment]
Yes it's possible. When accessing the container via a web browser, the resolution should be adjusted automatically according to the browser's window.

Otherwise, you can use the `DISPLAY_WIDTH` and `DISPLAY_HEIGHT` environment variables.  See https://github.com/jlesage/docker-firefox?tab=readme-ov-file#environment-variables

**Comment by jlesage** [comment]
Closing this issue. Please re-open if needed.
