### ISSUE TITLE
Error - Unsupported file format

### ISSUE THREAD

**Issue by bbakermmc** [jlesage/docker-firefox#25]
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
stored passwd in file: /root/.vncpass
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] check-snd.sh: executing...
[cont-init.d] check-snd.sh: sound not supported: device /dev/snd not exposed to the container.
[cont-init.d] check-snd.sh: exited 0.
[cont-init.d] firefox-set-prefs-from-env.sh: executing...
[cont-init.d] firefox-set-prefs-from-env.sh: exited 0.
[cont-init.d] firefox.sh: executing...
Error: unsupported file format

**Comment by jlesage** [comment]
On which device are you running the container?

**Comment by bbakermmc** [comment]
unraid

**Comment by bbakermmc** [comment]
Any update or how to use the previous version?

**Comment by jlesage** [comment]
The problem seems to be that you have corrupted file(s).  The files in question are `/config/profile/sessionstore-backups/*.jsonlz4` in the container (`/mnt/user/appdata/Firefox/profile/sessionstore-backups/*.jsonlz4` on the host).

You could try to try to start the container with a fresh appdata:
  - Stop the container.
  - Move the appdata folder: `mv /mnt/user/appdata/Firefox /mnt/user/appdata/Firefox.backup`
  - Start the container.
