### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by Azaverte** [jlesage/docker-firefox#7]
Hello! Thanks for your container, it's neat!

I would like to run it on openmediavault. It worked properly on an x86 VM, but if I try it on my ARM (armhf) single-board computer, the container crashes with the following error:

standard_init_linux.go:190: exec user process caused "exec format error"

which, if I understand well, is due to an architecture mismatch. Are you positive your container indeed can't run on ARM? If so, would it take you a lot of work to change dependencies?

**Comment by jlesage** [comment]
Hi, for this container to support ARM, 2 things are needed::
  1. Need to have a baseimage for the ARM architecture.
  2. Have Firefox compiled for ARM.

For 1), this is possible and I'm already working on adding support for multiple architectures.

For 2), Firefox is currently not available for ARM on Alpine Linux, which means that Firefox needs to compiled manually.  So for sure there will be some work to do on this side.

**Comment by DomiStyle** [comment]
> For 1), this is possible and I'm already working on adding support for multiple architectures.

Any ETA for ARM support for the baseimage?

**Comment by jlesage** [comment]
Since I work on this during my free time, it’s hard to give an ETA.  However, I can say that more than 90% of the work is done.

**Comment by DomiStyle** [comment]
> Since I work on this during my free time, it’s hard to give an ETA.

No rush, was just wondering how far it is.

> I can say that more than 90% of the work is done.

Good to hear, looking forward to it.

**Comment by kavejo** [comment]
+1 for the ARM support; just upping as this the last comment if from over an year ago.

**Comment by derjp** [comment]
+1

**Comment by mtis88** [comment]
+1

**Comment by mtis88** [comment]
I've built my own baseimage, baseimage-gui and firefox images for my RPi4. I had to change the firefox version to 75.0-r1 in the Dockerfile. Unfortunately after the image boots and firefox starts it immediately shutdowns (gracefully). I have used shm_size to set it to 2G and I've also tried mapping /dev/shm to my hosts /dev/shm. Any ideas?

**Comment by mtis88** [comment]
I'm trying to build my own baseimage and baseimage-gui for my RPi4 but the following tests fail: "Checking availability of VNC port 5900" and "Checking availability of VNC SSL port 5900". Any ideas?

**Comment by akarpenkoua** [comment]
+1 for ARM image. Will be grateful a lot! 
@mtis88 Have you succeeded with building the image? Can you share it? Or the Dockerfile script to reproduce your steps

**Comment by TheGeniusL** [comment]
+1

**Comment by TijnB** [comment]
@mtis88 If you managed to compile an image for RPi4, that would much anticipated.

**Comment by DBa2016** [comment]
> 
> 
> +1 for ARM image. Will be grateful a lot!
> @mtis88 Have you succeeded with building the image? Can you share it? Or the Dockerfile script to reproduce your steps

Though I'm not mtis88... :)
I went few steps down this road (I want to build a docker image with jd2 and firefox, or at least separately jd2 and ff for my raspi), not finished yet, but seems promising so far:
- clone the "baseimage" repository
- copy "Dockerfile.alpine" to "Dockerfile"
- change the "FROM" to base on "alpine:latest" 
- change S6_OVERLAY_ARCH and GLIBC_ARCH to "armhf" (my Raspi4 runs in armhf architecture right now, I am too lazy to fiddle with the sd card to resize the /boot partition...long story...). 
- build the image (takes a while, but not too long)
- git clone the baseimage-gui repo, copy Dockerfile.alpine to Dockerfile, change "FROM" to base on the tag you supplied when building "baseimage".
- build this image. This seems to take ages (no wonder, considering the compile amount there), I am at this step and will have it hopefully complete overnight (it is running on my Raspi, and I am not in a hurry).

I will report my progress here and maybe I'll start a fork...

**Comment by DBa2016** [comment]
Update:
- baseimage-gui built successfully (openssl dhparams is what took so awfully long), next steps see below
- git clone the jd2 repo
- update Dockerfile to use the baseimage-gui built above; also update it to install openjdk-8-jre (since no corretto is available for armhf architecture)
- build, run, fail because I forgot to update rootfs/startapp.sh to use the correct java path (/opt/jre/bin/java is for corretto, /usr/lib/jvm/java-1.8-openjdk/bin/java is for openjdk), correct rootfs/startapp.sh, build and run again (I am currently at this step, jd2 is now pulling updates)

Next steps are: clone docker-firefox repo, understand the build process, mange it into the above image, then build and run.

**Comment by DBa2016** [comment]
Another update: I managed to build the image and launch jd2 (not FF yet). An update of jd2 (something which should be done in 5 minutes tops) took more than 90 minutes on my Raspi4, so I am now trying a different approach, will see whether I get better performance and revisit this if the performance issue turns out to be caused by jd2/java.

**Comment by TijnB** [comment]
Great stuff, looking forward to your updates!

**Comment by DBa2016** [comment]
After exploring to that other solution, I returned to this base profile, the performance issue seems to be affecting more the update process (which can be executed during image creation to a major extent). Still trying to make firefox work, right now it errors out. Permission/directory issue, will maybe investigate tomorrow.

**Comment by DBa2016** [comment]
FF turned out to be super-slow on my pi4, so I went for falkon for now. Performance is stil meh, but better.
Valuable insights: switching to a 64-bit kernel halved build time. Docker itself is still 32bit though (since all userspace tools are 32bit), so arm64 images do not work. I will get a new SD card on Saturday and setup a pure arm64 pi4, hoping for another performance boost. For now, just the process of applying updates (after they have been downloaded) takes almost 25 minutes within the container (was worse before).

**Comment by MatthK** [comment]
Is there any update on this to run on a 64-bit Raspberry Pi?

**Comment by fhriley** [comment]
[I created a version that works on ARM](https://hub.docker.com/r/fhriley/firefox). It's not super fast, but it's usable on a Pi4.

**Comment by jlesage** [comment]
Latest image is now multi-arch.
